### ISSUE TITLE
res_life code

### ISSUE THREAD

**Issue by minhviet0308** [LutherAstrophysics/m23#13]
@wilkerje  We are looking at the res_life345 code. It uses the LINFIT function and does some strange arithmetic that we don't understand. It good really help if you can explain these to us.

**Comment by minhviet0308** [comment]
This code has been completed almost 3 months ago.

**Comment by sumanchapai** [comment]
During internight normalization, IDL tries to guess which star number a star is by looking at the reference file (file containing star x and y position in order of star no). For each star in the logfile combined file, it goes through the list of stars in the reference file until it finds one to which its distance is < 1 (a customizable impact threshold). 

This is problematic for a couple hundred stars (empirically speaking around 285 stars) that are close to each other.  For example, it thinks that 157 is star 157. BUT it also thinks that star 161 is star 157. This is because, when reading star 161's data from a log file, in order to find its star number,  it goes through the list of stars in the reference file and finds the first star that has < 1 distance with it. It, unfortunately, finds star 157 because stars 157 and 161 are very close. 

Precisely: 
Star 157 X,Y: 260.54, 284,4 
Star 161 X,Y: 260.46, 284.93 

This star is going to be marked absent for the image for that night, and other images for the night as well. This is the reason we see that star 161 doesn't have any data for any of the nights as we can see in the light curves website http://10.30.5.4:2300/lc/161 

This bugfix won't make much difference for the norm factor calculation because it just means that we are going to use these extra ~275 stars in calculation of normfactor for each image. This won't affect the median too much. Here is the difference. 1.006790002 0.995013355.

**Comment by sumanchapai** [comment]
Upon closer examination, this looks more like a feature than a bug. We really want to treat two indistinguishably close stars as a single star.
